blank_issues_enabled: false
contact_links:
  - name: Getting help
    url: https://link.lykos.ai/discord?ref=github-issue-template
    about: Ask questions about using Stability Matrix and get tips on using Packages on our Discord server
